### ISSUE TITLE
Sugestão: Jenkyll com Ruby

### ISSUE THREAD

**Issue by endersonmenezes** [brenopanzolini/ship-your-enemies-lgpd#1]
Bora fazer o site? Uma sugestão seria utilizar o Jenkyll com Ruby para deixar arquivado FAQ e essas coisas, e somente a manipulação de front da pra usar VUE rapidinho a gente constroi isso :)

**Comment by endersonmenezes** [comment]
@brenopanzolini :+1:

**Comment by brenopanzolini** [comment]
Oi @endersonmenezes, obrigado pelo interesse em participar 🙂.

Quanto a sugestão de stack realmente não tenho nada definido ainda, mas acho que Jekyll com Vue seria bem legal talvez.

**Comment by endersonmenezes** [comment]
Depois que fui ver seu perfil, talvez você possa ter mais experiência com isso haha
Você quer copiar a página do projeto original? Podiamos deixar algo preparado, e preparar os textos em Markdown sobre o FAQ, sobre até mesmo a LEI em si haha
Quando conheci o projeto externo da GDPR, ri durante muitos minutos e fui logo registrar o dominio da LGPD, achei o seu dominio registrado haha

**Comment by brenopanzolini** [comment]
Pois é, o site da GDPR é bem legal mesmo 🙂!

Quanto copiar o projeto original, acho que a ideia é sim se basear bastante nele, porém eu queria fazer algo um pouco mais "educativo" do que o da GDPR, até mesmo porque acho que aqui no Brasil as pessoas tem bem menos conhecimento dos seus direitos (falo por mim mesmo até). Então a ideia é sim ter o mesmo mecanismo principal mas também ser um pouco mais educativo nesse sentido.

Quanto aos textos, eu conversei com algumas pessoas interessadas em ajudar no projeto que manjam da lei de fato (eu até conheço um pouco, mas não me garanto a nível de escrever um texto 😂). Eu estava pensando em subir um site estático (podemos usar Jekyll mesmo) até o final da semana, pelo menos contendo algumas informações iniciais. E aí PRs vão ser bem-vindas 🚀. 

Como a LGPD vai entrar em vigor apenas em Agosto, acho legal segurar um pouco a versão final do site para mais perto dessa data.

**Comment by endersonmenezes** [comment]
E que tal a gente ir produzindo algum material, pode ser no Wiki aqui, eu trabalho diretamente com LGPD na empresa então tenho alguns textos e materiais interessantes.
Tenho um amigo advogado que adorou a ideia, tendo base educacional o projeto.

[O que acha desse template?](https://afterdata.in)

**Comment by brenopanzolini** [comment]
Ah legal que você conhece e também tem pessoas interessadas em ajudar, quanto mais gente dando opinião e visões diferentes melhor o resultado final :D. Acho a ideia do Wiki bem legal 💪.

Pra começar vou subir um template basicão mesmo, só pra página não ficar totalmente em branco e aí vamos interando e melhorando aos poucos!

**Comment by endersonmenezes** [comment]
Ok, vou ficar no seu comando, de verdade conte comigo pra realizar o que precisar haha!

**Comment by brenopanzolini** [comment]
@endersonmenezes abri uma PR bem básica só para não ficar com a página em branco. Já vou criar o **wiki** também.

Podemos também listar reportagens sobre empresas brasileiras que tiveram vazamento de dados!

_ps: estou fechando essa issue mas fique à vontade para reabrir ou abrir outras_
